#include <verilated.h>
#include "Vtrade_MEAN.h"    // Generated by Verilator from trade.sv
#include <fstream>
#include <iostream>

int main(int argc, char **argv, char **env) {
    Verilated::commandArgs(argc, argv);
    Vtrade_MEAN* top = new Vtrade_MEAN;

    // Open memory files to log buy/sell signals
    std::ofstream buy_file("buy_signal.mem");
    std::ofstream sell_file("sell_signal.mem");

    if (!buy_file.is_open() || !sell_file.is_open()) {
        std::cerr << "Error opening output files!" << std::endl;
        return 1;
    }

    // Simulation parameters
    const int NUM_CYCLES = 5000;
    top->rst = 1;
    top->clk = 0;

    // Apply reset for 2 clock cycles
    for (int i = 0; i < 2; i++) {
        top->clk = 0; top->eval();
        top->clk = 1; top->eval();
    }
    top->rst = 0;

    // Main simulation loop
    for (int cycle = 0; cycle < NUM_CYCLES; cycle++) {
        // Rising edge
        top->clk = 1;
        top->eval();

        // Write buy/sell signals as 0 or 1
        buy_file  << (int)top->buy_signal  << std::endl;
        sell_file << (int)top->sell_signal << std::endl;

        // Falling edge
        top->clk = 0;
        top->eval();
    }

    buy_file.close();
    sell_file.close();
    delete top;
    return 0;
}

