// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vtrade_SMA.cpp"
#include "Vtrade_SMA___024root__DepSet_h783b4b1a__0.cpp"
#include "Vtrade_SMA___024root__Slow.cpp"
#include "Vtrade_SMA___024root__DepSet_h783b4b1a__0__Slow.cpp"
#include "Vtrade_SMA__Syms.cpp"
